{{- if not .Values.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-vmware-exporter.secretName" . }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus-vmware-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.vmware.host | b64enc }}
  username: {{ .Values.vmware.username | b64enc }}
  password: {{ .Values.vmware.password | b64enc }}
  log: {{ .Values.vmware.log | b64enc }}
{{- end }}